### ISSUE TITLE
job queue not found

### ISSUE THREAD

**Issue by zdk123** [base2genomics/batchit#13]
I guess I am missing some details about the setup here, but I am getting the message:

```
panic: error submitting job: : JobQueue x-job-queue not found.
	status code: 400, request id: YYYYYYYYYYYYY
```

Though I have:
```
aws batch describe-job-queues --job-queues x-job-queue
{
    "jobQueues": [
        {
            "jobQueueName": "x-job-queue",
...
```

I guess this will be difficult to debug, but I believe all the roles are setup correctly, as per the readme.

Any suggestions? 

thanks!

**Comment by brentp** [comment]
did you tell batchit your region, it defaults to us-east-1 or 2

**Comment by zdk123** [comment]
yup that was it. Thanks!
