### ISSUE TITLE
batchit clobbers PATH 

### ISSUE THREAD

**Issue by leipzig** [base2genomics/batchit#7]
Hi I am seeing this directive as part of the batchit boilerplate:
`fi set +a if [ -f /etc/profile ]; then source /etc/profile;`

and I fear that is effectively clobbering any `ENV PATH` I might set in the Dockerfile itself.

Is there a way to quell this behavior?

**Comment by brentp** [comment]
is this a problem in practice? I actually blindly copied that from aegea and I'm not sure of the full consequences.

**Comment by leipzig** [comment]
Yes I'll cook up an reproducible example

**Comment by leipzig** [comment]
```
sudo docker run -it quay.io/leipzig/testbatchit
(base) root@e6c9e33dd27f:/# echo $PATH
/opt/conda/bin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

```
batchit submit --image quay.io/leipzig/testbatchit --role ecsTaskRole --queue rightnow --jobname infopath --cpus 1 --mem 2000 --ebs /mnt/my-ebs:500:st1:ext4 script:'echo $PATH'
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

So I guess a workaroud could be as simple as `dockerPath=$PATH;source /etc/profile;export PATH=$PATH:$dockerPath`

**Comment by brentp** [comment]
well, this could also be the difference between your interactive $SHELL using docker run vs a non-interactive in batch.

I think it's safe to remove that statement anyway, I'm just hesitant in case there's some unforeseen consequence.

**Comment by leipzig** [comment]
i have removed this line from batchit with no ill consequences

**Comment by brentp** [comment]
ok. thanks for following up. I have removed this. It will be out in next release.

**Comment by leipzig** [comment]
well it's the `/etc/profile` that clobbers the PATH. looks like you removed `/etc/environment`
