### ISSUE TITLE
submit with --ebs not cleaning up EBS volumes

### ISSUE THREAD

**Issue by tomazberisa** [base2genomics/batchit#8]
When submitting a job with the `--ebs` option, the created EBS volume is not cleaned up from the EC2 instance, rather it stays attached to the EC2 instance for the duration of the instance lifetime.

I suspect this `trap` command:
https://github.com/base2genomics/batchit/blob/master/submit/submit.go#L116
overrides this `trap` command:
https://github.com/base2genomics/batchit/blob/master/submit/submit.go#L218

**Comment by brentp** [comment]
something else must be going on because we run thousands of jobs and the ebs volumes get cleaned up. I'm fine with adding the PR if you verify that it resolve your particular issue (and updates to address my comment).

**Comment by tomazberisa** [comment]
Just curious, do your ebs volumes get cleaned up on instance termination or right upon job completion? 
On our end, I can confirm they are cleaned up on instance termination (as a consequence of the `DeletionOnTermination` attribute being set), but not on job completion.

**Comment by brentp** [comment]
I am almost certain they are cleanup on job completion.

**Comment by tomazberisa** [comment]
Interesting. Maybe it's best not to accept the pull request then. 
I'm happy to maintain this fix in the forked repo for ourselves until we can pin down the root cause.

**Comment by brentp** [comment]
I'd be happy to accept the PR. Perhaps I am mistaken. I had though that given e.g.
```
trap "echo asdf" EXIT
trap "echo 1234" EXIT
```
both traps would fire. but that is not the case so the code as-is should not cleanup.

**Comment by tomazberisa** [comment]
Think I might have gotten to the bottom of this. We are using both `--ebs` and `--volumes`, in which case both trap commands run, and the second one overrides the first. This situation introduced the need for this fix. 
If only `--ebs` is used (which might be your case?), then volumes should have been properly cleaned up prior to applying this fix.

**Comment by brentp** [comment]
ah. yeah. that must be it. I rarely/never use --volumes.
